class DomainError(Exception): ...


class DomainPermissionDenied(DomainError): ...


class EntityNotFoundError(DomainError): ...


class DomainConflictError(DomainError): ...


class DomainRuleViolation(DomainError): ...


class ValueObjectError(DomainError): ...
