"""empty message

Revision ID: 0e7af3faf5a7
Revises: a79dc5a770c6
Create Date: 2026-06-18 03:34:25.810276

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0e7af3faf5a7"
down_revision: str | Sequence[str] | None = "a79dc5a770c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("reg_at", sa.DateTime(timezone=True), nullable=False)
    )
    op.drop_column("User", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("User", "reg_at")
    # ### end Alembic commands ###
