"""empty message

Revision ID: a79dc5a770c6
Revises:
Create Date: 2026-06-18 03:33:50.421993

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a79dc5a770c6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_User")),
    )
    op.create_table(
        "UserCredentials",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["User.id"], name=op.f("fk_UserCredentials_user_id_User")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_UserCredentials")),
    )
    op.create_index(
        op.f("ix_UserCredentials_login"), "UserCredentials", ["login"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_UserCredentials_login"), table_name="UserCredentials")
    op.drop_table("UserCredentials")
    op.drop_table("User")
    # ### end Alembic commands ###
